In [42]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [43]:
dataset = pd.read_csv('/app/Embedding/dataframes/doc2vet_embedding.csv')
dataset.head()


0         1         2         3         4         5         6  \
0  2.006918  0.475260  2.533349 -0.547314  1.839901  0.480708 -1.371269   
1 -1.121114 -0.079858  1.176407  1.838457 -0.643866  1.464561  1.980504   
2 -0.568313  1.174308  1.701519 -0.404837  0.131735  1.160653 -1.027584   
3  0.961319  0.191656  0.334632  0.193879  0.552590  0.267899 -1.982957   
4  0.031784  0.415218  1.714118 -1.906597 -0.477352 -0.855979 -0.079660   

          7         8         9  ...        41        42        43        44  \
0  0.344498 -0.874812  0.006530  ... -1.938029 -1.270428 -0.673977  1.488535   
1  1.601531 -2.236448 -0.542896  ... -0.597759 -1.340720 -2.803389  2.953959   
2 -0.188119 -0.467599 -0.438443  ...  1.412459 -0.096511 -0.078653  0.320290   
3  0.645889  0.676048  0.659063  ... -0.524286  2.590564  1.319239  1.085825   
4  0.510074  1.183520 -0.703154  ...  1.316142  2.843449  0.487614 -0.336858   

         45        46        47        48        49                  50  
0 -1.210708  0.018973 -2.066191 -2.047388  0.340610     computer vision  
1  2.749169 -0.246176  0.167863  2.535898  2.245542           political  
2 -0.105544  1.505233 -0.254141 -0.322210  1.313339  autonomous vehicle  
3  2.282317 -1.031726 -0.018153 -0.474326  0.046656     computer vision  
4  1.732589  0.694663 -0.933902 -1.002878  0.285510     computer vision  

[5 rows x 51 columns]

In [44]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 50].values

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10)

In [46]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=8)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [48]:
y_pred = classifier.predict(X_test)

In [49]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[899   1  21  21   1   5  33   9   0]
 [  0 130   1   1   0   0   0   3   0]
 [ 79   7 795   8  62  11  23  22   0]
 [ 58  34  53 661  75  28  69  24   4]
 [ 33  26  96  33 736   3  18  26   0]
 [ 36  17  27  54  11 183  61   5   4]
 [207  19  39  69  12  58 614   6   1]
 [  0   4   0   2   0   1   0 264   0]
 [  0   0   0  16  14   2   0   2   9]]
                    precision    recall  f1-score   support

                5g       0.69      0.91      0.78       990
           anxiety       0.55      0.96      0.70       135
autonomous vehicle       0.77      0.79      0.78      1007
          big data       0.76      0.66      0.71      1006
   computer vision       0.81      0.76      0.78       971
     cybersecurity       0.63      0.46      0.53       398
               iot       0.75      0.60      0.67      1025
         political       0.73      0.97      0.84       271
sentence embedding       0.50      0.21      0.30        43

          accuracy                           0