In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
# dataset = pd.read_csv('/app/Embedding/dataframes/doc2vet_embedding.csv')
# dataset = pd.read_csv('/app/Embedding/dataframes/infer_sent_embedding.csv')
# dataset = pd.read_csv('/app/Embedding/dataframes/sentence_bert_embedding.csv')
dataset = pd.read_csv('/app/Embedding/dataframes/universal_sentence_python.csv')
dataset.head()

0.011135019  -0.034410488  -0.05080807  0.0082706865  0.044154685  \
0     0.055683      0.056129     0.032918     -0.054384     0.057507   
1     0.011289      0.062801    -0.051032     -0.061473     0.049657   
2    -0.018277     -0.055102     0.028916      0.008216    -0.055602   
3    -0.033637     -0.040760    -0.048334      0.010415     0.035124   
4    -0.034683     -0.020007    -0.038721     -0.056459     0.033053   

   0.046885874  -0.002305564  0.033856846  -0.011727817  0.060213666  ...  \
0    -0.056221      0.021612    -0.038179      0.057070     0.051451  ...   
1    -0.041211     -0.032785     0.052089     -0.063731     0.049298  ...   
2    -0.054291     -0.042487    -0.003218      0.002576     0.012928  ...   
3    -0.040053      0.056717     0.059027      0.041808    -0.003748  ...   
4     0.025431     -0.045199     0.028089      0.057768     0.054189  ...   

   -0.06272057  -0.0145490775  -0.06080339  0.022973256  -0.024654124  \
0    -0.058993      -0.053008    -0.053664     0.033262      0.057798   
1    -0.068041      -0.065129    -0.027780     0.062614      0.010739   
2    -0.061408      -0.017785    -0.053553     0.056751     -0.049993   
3    -0.070625      -0.057200     0.016933     0.061258      0.011347   
4    -0.062242      -0.043655     0.045409    -0.040571      0.061975   

   0.06089911  0.033888433  -0.017606566  -0.05352775             anxiety  
0    0.003701    -0.021499     -0.054971    -0.012387  autonomous vehicle  
1    0.059879     0.040236     -0.022578     0.000560                 iot  
2   -0.028755     0.047430     -0.058397    -0.013559       cybersecurity  
3    0.045915     0.047511     -0.065168     0.043834                  5g  
4    0.035103     0.061329     -0.057664    -0.024088  autonomous vehicle  

[5 rows x 513 columns]

In [27]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 512].values
y = pd.factorize(y)[0]

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [29]:
X = scaler.transform(X)

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10)

In [31]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=4)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [32]:
y_pred = classifier.predict(X_test)

In [33]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[863  29  13  23   7  21   0   0   0]
 [ 44 823  18  70  48  18   0   0   1]
 [ 40  85 186  20  57  17   0   0   0]
 [ 38 108  12 829  18   6   0   0   1]
 [ 43 114  30  23 725  79   3   2   7]
 [ 95  24  12   5  56 754   0   2   1]
 [  2   1   1   0   4   3 250   3   0]
 [  0   0   1   0   1   1   1 150   0]
 [  1   1   0   0  14  11   0   0  31]]
              precision    recall  f1-score   support

           0       0.77      0.90      0.83       956
           1       0.69      0.81      0.75      1022
           2       0.68      0.46      0.55       405
           3       0.85      0.82      0.84      1012
           4       0.78      0.71      0.74      1026
           5       0.83      0.79      0.81       949
           6       0.98      0.95      0.97       264
           7       0.96      0.97      0.96       154
           8       0.76      0.53      0.63        58

    accuracy                           0.79      5846
   macro avg       0.81      0.77      0.79      584

In [34]:
from sklearn.model_selection import KFold, cross_val_score

n_splits = 10
kf = KFold(n_splits)

scores = cross_val_score(classifier, X, y, cv=10, scoring='accuracy')
print(scores)

[0.7949025  0.78994184 0.78977078 0.78857338 0.8032843  0.79148135
 0.79387615 0.79178785 0.79041916 0.79007699]
