In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('../dataframes/doc2vet_embedding.csv', header=None)
# dataset = pd.read_csv('../dataframes/infer_sent_embedding.csv')
# dataset = pd.read_csv('../dataframes/sentence_bert_embedding.csv')
# dataset = pd.read_csv('../dataframes/universal_sentence_python.csv')
dataset.head()

0         1         2         3         4         5         6   \
0 -1.214745 -0.283617 -1.270768  1.537702 -0.459085 -0.993889  2.742131   
1 -0.239725  0.531531  2.088746 -0.950215 -0.696374  0.358628 -0.472627   
2  0.251089  1.065683  1.103420 -0.405558  0.289183  0.889629 -0.157562   
3 -0.207214 -0.572141 -1.050872 -0.334811 -1.112067 -0.778233  1.201863   
4 -0.009177  0.003597 -0.008110  0.000640  0.009924 -0.009576  0.006663   

         7         8         9   ...        41        42        43        44  \
0  1.059220 -1.893328 -1.928233  ...  1.094292 -2.132212  0.469998 -0.944596   
1  0.071855 -2.446701  0.841731  ...  0.208730 -2.264483 -0.659729  1.239643   
2  0.810174  0.685724 -0.056801  ... -1.241523  0.386352 -0.323743 -0.911326   
3  1.173641 -1.249250  0.795089  ... -0.514634  0.089595  1.131394 -1.147426   
4  0.003818  0.003186  0.007003  ...  0.004158 -0.008099  0.008873  0.004717   

         45        46        47        48        49             50  
0  1.293732 -0.647479  0.219317 -1.710796 -0.109420       big_data  
1 -0.275169 -0.536493 -1.578909 -0.830742 -1.613818             5g  
2 -1.623940  0.084220  0.276691  0.368230  1.331997             5g  
3  0.626237  0.194895 -0.360906  1.163492 -0.407590  cybersecurity  
4  0.008786  0.000854 -0.009387 -0.005372 -0.002226        anxiety  

[5 rows x 51 columns]

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
y = pd.factorize(y)[0]

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [8]:
X = scaler.transform(X)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=4)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[714  46  37  23  79  30  19  65   6]
 [ 32 912  15   3  52  26   2   0   0]
 [ 59  37 184   5  49  11   4  12   1]
 [  2   1   2 172   0   0   1   0   0]
 [100 236  77   7 579  35   4  21   1]
 [ 37 105  22   2  25 717   7  56   0]
 [  3   0   1   2   0   0 218   0   0]
 [ 63  47  28  23  45 140  16 595   3]
 [ 13   0   5   1   0   0   0  18  19]]
              precision    recall  f1-score   support

           0       0.70      0.70      0.70      1019
           1       0.66      0.88      0.75      1042
           2       0.50      0.51      0.50       362
           3       0.72      0.97      0.83       178
           4       0.70      0.55      0.61      1060
           5       0.75      0.74      0.74       971
           6       0.80      0.97      0.88       224
           7       0.78      0.62      0.69       960
           8       0.63      0.34      0.44        56

    accuracy                           0.70      5872
   macro avg       0.69      0.70      0.68      587

In [34]:
from sklearn.model_selection import KFold, cross_val_score

n_splits = 10
kf = KFold(n_splits)

scores = cross_val_score(classifier, X, y, cv=10, scoring='accuracy')
print(scores)

[0.7949025  0.78994184 0.78977078 0.78857338 0.8032843  0.79148135
 0.79387615 0.79178785 0.79041916 0.79007699]
